<!DOCTYPE html>
<html lang="en" ng-app="taskConfirmationApp">
  <head>
    <meta charset="utf-8" />
    <title><?= APP_TITLE ?> | <?= $this->title ?></title>
    <meta name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=yes">
    <?= $this->headMeta() ?>
    <link rel="icon" href="/favicon.png" type="image/png">
    <link rel="shortcut icon" href="/favicon.ico">
    <?= $this->headLink()?>
    <link href="https://www.vreasy.com/angular/vreasy.css" rel="stylesheet">
    <script type="text/javascript" src="/bower_components/angular/angular.min.js"></script>
    <script type="text/javascript" src="/bower_components/lodash/dist/lodash.min.js"></script>
    <script type="text/javascript" src="/bower_components/angular-ui-router/release/angular-ui-router.min.js"></script>
    <script type="text/javascript" src="/bower_components/angular-resource/angular-resource.min.js"></script>
    <script type="text/javascript" src="/taskConfirmationApp/app.js"></script>
  </head>
  <body>
    <div class="vr-nav-bar">
      <nav role="navigation" >
        <div>
          <div class="navbar-header">
            <a href="/" title="{{ appName }}" class="navbar-brand">
              <img src="https://www.vreasy.com/img/vreasy-logo-svg.svg" height="60">
            </a>
          </div>
        </div>
      </nav>
    </div>
    <div class="container main-view-wrapper"
        id="vreasy-main-container"
        style="position: relative;">
            <?= $this->layout()->content; ?>
    </div>
    <hr>
    <div class="container">
      <footer>
        <p class="ar copyright pull-right">
            <small>
              &copy; <?= APP_TITLE ?> <?= date('Y') ?> version <?= APP_VERSION ?> <?= APPLICATION_ENV == 'production' ? '' : APPLICATION_ENV ?>
            </small>
        </p>
      </footer>
   </div>
  </body>
</html>
